export type Diet = "vegan" | "vegetarian" | "eggetarian" | "non-vegetarian";

export type MealType =
  | "breakfast"
  | "morning_snack"
  | "lunch"
  | "evening_snack"
  | "dinner";

export type Ingredient = {
  name: string;
  qty?: string;
  optional?: boolean;
};

export type Recipe = {
  id: string;
  name: string;
  blurb: string;
  diet: Diet;
  mealType: MealType;
  prepMinutes: number;
  ingredients: Ingredient[];
  steps: string[];
  cuisine?: string;
};

export const MEAL_TYPES: MealType[] = [
  "breakfast",
  "morning_snack",
  "lunch",
  "evening_snack",
  "dinner",
];

export const MEAL_LABELS: Record<MealType, string> = {
  breakfast: "Breakfast",
  morning_snack: "Morning Snack",
  lunch: "Lunch",
  evening_snack: "Evening Snack",
  dinner: "Dinner",
};

export const MEAL_TIME_HINT: Record<MealType, string> = {
  breakfast: "7 – 9 AM",
  morning_snack: "10 – 11 AM",
  lunch: "12:30 – 2 PM",
  evening_snack: "4:30 – 6 PM",
  dinner: "7:30 – 9 PM",
};

export const DIET_LABELS: Record<Diet, string> = {
  vegan: "Vegan",
  vegetarian: "Vegetarian",
  eggetarian: "Eggetarian",
  "non-vegetarian": "Non-Vegetarian",
};

export const DIET_DESCRIPTIONS: Record<Diet, string> = {
  vegan: "No animal products at all.",
  vegetarian: "Plants and dairy. No eggs, no meat.",
  eggetarian: "Vegetarian plus eggs.",
  "non-vegetarian": "Anything goes — meat, fish, eggs, dairy.",
};

export function dietAllows(userDiet: Diet, recipeDiet: Diet): boolean {
  if (userDiet === "vegan") return recipeDiet === "vegan";
  if (userDiet === "vegetarian")
    return recipeDiet === "vegan" || recipeDiet === "vegetarian";
  if (userDiet === "eggetarian")
    return (
      recipeDiet === "vegan" ||
      recipeDiet === "vegetarian" ||
      recipeDiet === "eggetarian"
    );
  return true;
}

export const RECIPES: Recipe[] = [
  // ============== BREAKFAST ==============
  {
    id: "b-oats-banana",
    name: "Banana Oat Bowl",
    blurb: "Creamy overnight oats topped with sliced banana and honey.",
    diet: "vegetarian",
    mealType: "breakfast",
    prepMinutes: 5,
    ingredients: [
      { name: "oats", qty: "1/2 cup" },
      { name: "milk", qty: "3/4 cup" },
      { name: "banana", qty: "1" },
      { name: "honey", qty: "1 tbsp", optional: true },
      { name: "cinnamon", qty: "a pinch", optional: true },
    ],
    steps: [
      "Combine oats and milk in a bowl, let sit 5 minutes (or overnight).",
      "Top with sliced banana, drizzle of honey and a pinch of cinnamon.",
    ],
  },
  {
    id: "b-avocado-toast",
    name: "Smashed Avocado Toast",
    blurb: "Crusty bread, ripe avocado, lemon and chili flakes.",
    diet: "vegan",
    mealType: "breakfast",
    prepMinutes: 8,
    ingredients: [
      { name: "bread", qty: "2 slices" },
      { name: "avocado", qty: "1" },
      { name: "lemon", qty: "1/2" },
      { name: "salt", qty: "to taste" },
      { name: "chili flakes", qty: "a pinch", optional: true },
    ],
    steps: [
      "Toast the bread.",
      "Mash avocado with lemon juice and salt.",
      "Pile on toast and finish with chili flakes.",
    ],
  },
  {
    id: "b-veg-poha",
    name: "Vegetable Poha",
    blurb: "Light, lemony flattened rice with peas and peanuts.",
    diet: "vegan",
    mealType: "breakfast",
    prepMinutes: 15,
    cuisine: "Indian",
    ingredients: [
      { name: "poha", qty: "1 cup" },
      { name: "onion", qty: "1" },
      { name: "potato", qty: "1" },
      { name: "peas", qty: "1/4 cup", optional: true },
      { name: "peanuts", qty: "2 tbsp" },
      { name: "mustard seeds", qty: "1/2 tsp" },
      { name: "turmeric", qty: "1/4 tsp" },
      { name: "lemon", qty: "1/2" },
      { name: "curry leaves", qty: "a few", optional: true },
      { name: "oil", qty: "1 tbsp" },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Rinse and drain poha; set aside.",
      "Temper mustard seeds, peanuts and curry leaves in oil.",
      "Add onion and potato, cook till tender.",
      "Stir in turmeric, peas, salt, then poha.",
      "Cover for 2 min, finish with lemon juice.",
    ],
  },
  {
    id: "b-masala-omelette",
    name: "Masala Omelette",
    blurb: "Fluffy omelette with onion, tomato and green chili.",
    diet: "eggetarian",
    mealType: "breakfast",
    prepMinutes: 10,
    cuisine: "Indian",
    ingredients: [
      { name: "eggs", qty: "2" },
      { name: "onion", qty: "1/2" },
      { name: "tomato", qty: "1/2" },
      { name: "green chili", qty: "1", optional: true },
      { name: "coriander", qty: "a few sprigs", optional: true },
      { name: "salt", qty: "to taste" },
      { name: "oil", qty: "1 tsp" },
    ],
    steps: [
      "Whisk eggs with finely chopped veg and salt.",
      "Pour into a hot oiled pan, cook 1–2 min per side.",
      "Fold and serve hot.",
    ],
  },
  {
    id: "b-scrambled-eggs",
    name: "Soft Scrambled Eggs",
    blurb: "Buttery, cloud-soft eggs on toast.",
    diet: "eggetarian",
    mealType: "breakfast",
    prepMinutes: 8,
    ingredients: [
      { name: "eggs", qty: "3" },
      { name: "butter", qty: "1 tbsp" },
      { name: "milk", qty: "2 tbsp", optional: true },
      { name: "salt", qty: "to taste" },
      { name: "bread", qty: "2 slices", optional: true },
    ],
    steps: [
      "Whisk eggs with milk and salt.",
      "Cook gently in butter, stirring constantly, until just set.",
      "Serve over toast.",
    ],
  },
  {
    id: "b-yogurt-parfait",
    name: "Berry Yogurt Parfait",
    blurb: "Layered yogurt, granola and seasonal berries.",
    diet: "vegetarian",
    mealType: "breakfast",
    prepMinutes: 5,
    ingredients: [
      { name: "yogurt", qty: "1 cup" },
      { name: "granola", qty: "1/3 cup" },
      { name: "berries", qty: "1/2 cup" },
      { name: "honey", qty: "1 tsp", optional: true },
    ],
    steps: [
      "Layer yogurt, granola and berries in a glass.",
      "Repeat layers and finish with a drizzle of honey.",
    ],
  },
  {
    id: "b-chicken-sausage-skillet",
    name: "Chicken Sausage Skillet",
    blurb: "Sausage, peppers and eggs in one hot pan.",
    diet: "non-vegetarian",
    mealType: "breakfast",
    prepMinutes: 15,
    ingredients: [
      { name: "chicken sausage", qty: "2" },
      { name: "bell pepper", qty: "1" },
      { name: "onion", qty: "1/2" },
      { name: "eggs", qty: "2" },
      { name: "oil", qty: "1 tbsp" },
      { name: "salt", qty: "to taste" },
      { name: "pepper", qty: "to taste" },
    ],
    steps: [
      "Slice and brown the sausage in oil.",
      "Add onion and bell pepper; cook till soft.",
      "Crack eggs over top, cover and cook till set.",
    ],
  },

  // ============== MORNING SNACK ==============
  {
    id: "ms-fruit-bowl",
    name: "Fresh Fruit Bowl",
    blurb: "Whatever fruit you have, chopped and chilled.",
    diet: "vegan",
    mealType: "morning_snack",
    prepMinutes: 5,
    ingredients: [
      { name: "apple", qty: "1", optional: true },
      { name: "banana", qty: "1", optional: true },
      { name: "orange", qty: "1", optional: true },
      { name: "berries", qty: "1/2 cup", optional: true },
      { name: "lemon", qty: "1/2", optional: true },
    ],
    steps: [
      "Chop fruit into bite-size pieces.",
      "Squeeze lemon over apple/banana to keep them bright.",
    ],
  },
  {
    id: "ms-hummus-veggies",
    name: "Hummus with Veggie Sticks",
    blurb: "Crunchy carrots and cucumber with creamy hummus.",
    diet: "vegan",
    mealType: "morning_snack",
    prepMinutes: 5,
    ingredients: [
      { name: "hummus", qty: "1/2 cup" },
      { name: "carrot", qty: "1" },
      { name: "cucumber", qty: "1" },
      { name: "bell pepper", qty: "1", optional: true },
    ],
    steps: [
      "Cut vegetables into thin sticks.",
      "Serve alongside hummus.",
    ],
  },
  {
    id: "ms-trail-mix",
    name: "DIY Trail Mix",
    blurb: "Nuts, seeds and dried fruit by the handful.",
    diet: "vegan",
    mealType: "morning_snack",
    prepMinutes: 2,
    ingredients: [
      { name: "almonds", qty: "1/4 cup" },
      { name: "peanuts", qty: "1/4 cup", optional: true },
      { name: "raisins", qty: "2 tbsp" },
      { name: "sunflower seeds", qty: "1 tbsp", optional: true },
    ],
    steps: ["Toss everything together. That's it."],
  },
  {
    id: "ms-banana-pb",
    name: "Banana with Peanut Butter",
    blurb: "Sliced banana with a smear of peanut butter.",
    diet: "vegan",
    mealType: "morning_snack",
    prepMinutes: 3,
    ingredients: [
      { name: "banana", qty: "1" },
      { name: "peanut butter", qty: "2 tbsp" },
    ],
    steps: [
      "Slice banana lengthwise.",
      "Spread peanut butter over the cut side.",
    ],
  },
  {
    id: "ms-paneer-tikka-bites",
    name: "Paneer Tikka Bites",
    blurb: "Quick spiced paneer cubes in a hot pan.",
    diet: "vegetarian",
    mealType: "morning_snack",
    prepMinutes: 12,
    cuisine: "Indian",
    ingredients: [
      { name: "paneer", qty: "200g" },
      { name: "yogurt", qty: "2 tbsp" },
      { name: "garam masala", qty: "1 tsp" },
      { name: "turmeric", qty: "1/4 tsp" },
      { name: "ginger garlic paste", qty: "1 tsp" },
      { name: "lemon", qty: "1/2" },
      { name: "oil", qty: "1 tbsp" },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Marinate paneer cubes in yogurt and spices for 5 minutes.",
      "Sear in oil till golden on all sides.",
      "Squeeze lemon over and serve.",
    ],
  },
  {
    id: "ms-boiled-eggs",
    name: "Boiled Eggs with Salt & Pepper",
    blurb: "Two eggs, hot pinch of seasoning. Done.",
    diet: "eggetarian",
    mealType: "morning_snack",
    prepMinutes: 10,
    ingredients: [
      { name: "eggs", qty: "2" },
      { name: "salt", qty: "to taste" },
      { name: "pepper", qty: "to taste" },
    ],
    steps: [
      "Boil eggs for 8–9 minutes.",
      "Cool, peel and season generously.",
    ],
  },

  // ============== LUNCH ==============
  {
    id: "l-dal-rice",
    name: "Dal & Rice",
    blurb: "Comforting yellow lentils over fluffy rice.",
    diet: "vegan",
    mealType: "lunch",
    prepMinutes: 30,
    cuisine: "Indian",
    ingredients: [
      { name: "rice", qty: "1 cup" },
      { name: "dal", qty: "1 cup" },
      { name: "onion", qty: "1" },
      { name: "tomato", qty: "1" },
      { name: "ginger", qty: "1 inch" },
      { name: "garlic", qty: "3 cloves" },
      { name: "turmeric", qty: "1/2 tsp" },
      { name: "cumin seeds", qty: "1 tsp" },
      { name: "oil", qty: "1 tbsp" },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Cook rice as usual.",
      "Pressure cook dal with turmeric and salt till soft.",
      "Temper cumin in oil with onion, ginger, garlic, then tomato.",
      "Pour temper over dal and serve with rice.",
    ],
  },
  {
    id: "l-chickpea-salad",
    name: "Mediterranean Chickpea Salad",
    blurb: "Bright bowl of chickpeas, cucumber and herbs.",
    diet: "vegan",
    mealType: "lunch",
    prepMinutes: 10,
    ingredients: [
      { name: "chickpeas", qty: "1 can" },
      { name: "cucumber", qty: "1" },
      { name: "tomato", qty: "1" },
      { name: "onion", qty: "1/2" },
      { name: "olive oil", qty: "2 tbsp" },
      { name: "lemon", qty: "1" },
      { name: "parsley", qty: "a handful", optional: true },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Drain chickpeas; chop the vegetables small.",
      "Toss with olive oil, lemon juice, salt and parsley.",
    ],
  },
  {
    id: "l-veg-fried-rice",
    name: "Veggie Fried Rice",
    blurb: "Wok-tossed rice with whatever veg is in the fridge.",
    diet: "vegan",
    mealType: "lunch",
    prepMinutes: 20,
    ingredients: [
      { name: "rice", qty: "2 cups cooked" },
      { name: "carrot", qty: "1" },
      { name: "bell pepper", qty: "1" },
      { name: "onion", qty: "1" },
      { name: "garlic", qty: "3 cloves" },
      { name: "soy sauce", qty: "2 tbsp" },
      { name: "oil", qty: "2 tbsp" },
      { name: "spring onion", qty: "2 stalks", optional: true },
      { name: "peas", qty: "1/4 cup", optional: true },
    ],
    steps: [
      "Heat oil; add garlic and onion, then carrot and pepper.",
      "Toss in cold cooked rice and soy sauce.",
      "Stir-fry on high heat 2–3 minutes; finish with spring onion.",
    ],
  },
  {
    id: "l-pasta-pomodoro",
    name: "Pasta Pomodoro",
    blurb: "Simple tomato and basil pasta the right way.",
    diet: "vegan",
    mealType: "lunch",
    prepMinutes: 20,
    ingredients: [
      { name: "pasta", qty: "200g" },
      { name: "tomato", qty: "4" },
      { name: "garlic", qty: "3 cloves" },
      { name: "olive oil", qty: "3 tbsp" },
      { name: "basil", qty: "a handful", optional: true },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Boil pasta in salted water.",
      "Sauté garlic in olive oil; add chopped tomato, simmer 8 min.",
      "Toss pasta in sauce, finish with basil.",
    ],
  },
  {
    id: "l-paneer-bhurji",
    name: "Paneer Bhurji",
    blurb: "Crumbled paneer scrambled with onion and spices.",
    diet: "vegetarian",
    mealType: "lunch",
    prepMinutes: 20,
    cuisine: "Indian",
    ingredients: [
      { name: "paneer", qty: "200g" },
      { name: "onion", qty: "1" },
      { name: "tomato", qty: "1" },
      { name: "green chili", qty: "1", optional: true },
      { name: "ginger", qty: "1 inch" },
      { name: "turmeric", qty: "1/4 tsp" },
      { name: "garam masala", qty: "1/2 tsp" },
      { name: "oil", qty: "1 tbsp" },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Sauté onion, ginger and chili in oil.",
      "Add tomato and spices, cook till mushy.",
      "Stir in crumbled paneer; cook 3 min.",
    ],
  },
  {
    id: "l-egg-curry",
    name: "Egg Curry",
    blurb: "Boiled eggs simmered in a tomato-onion masala.",
    diet: "eggetarian",
    mealType: "lunch",
    prepMinutes: 25,
    cuisine: "Indian",
    ingredients: [
      { name: "eggs", qty: "4" },
      { name: "onion", qty: "2" },
      { name: "tomato", qty: "2" },
      { name: "ginger garlic paste", qty: "1 tbsp" },
      { name: "turmeric", qty: "1/2 tsp" },
      { name: "garam masala", qty: "1 tsp" },
      { name: "chili powder", qty: "1 tsp" },
      { name: "oil", qty: "2 tbsp" },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Boil and peel eggs.",
      "Brown onion in oil, add ginger garlic paste.",
      "Add tomato and spices, cook till oil splits.",
      "Slip in eggs, simmer 5 min in 1 cup water.",
    ],
  },
  {
    id: "l-chicken-curry",
    name: "Chicken Curry",
    blurb: "Classic homestyle curry over rice.",
    diet: "non-vegetarian",
    mealType: "lunch",
    prepMinutes: 40,
    cuisine: "Indian",
    ingredients: [
      { name: "chicken", qty: "500g" },
      { name: "onion", qty: "2" },
      { name: "tomato", qty: "2" },
      { name: "ginger garlic paste", qty: "1 tbsp" },
      { name: "yogurt", qty: "1/4 cup" },
      { name: "turmeric", qty: "1/2 tsp" },
      { name: "garam masala", qty: "1 tsp" },
      { name: "chili powder", qty: "1 tsp" },
      { name: "oil", qty: "3 tbsp" },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Brown onion in oil, add ginger garlic paste.",
      "Stir in tomato, yogurt and spices till oil splits.",
      "Add chicken and 1.5 cups water; simmer 25 min.",
    ],
  },
  {
    id: "l-grilled-chicken-bowl",
    name: "Grilled Chicken Rice Bowl",
    blurb: "Charred chicken, rice, salad and a drizzle of yogurt.",
    diet: "non-vegetarian",
    mealType: "lunch",
    prepMinutes: 25,
    ingredients: [
      { name: "chicken", qty: "300g" },
      { name: "rice", qty: "1 cup" },
      { name: "yogurt", qty: "1/4 cup" },
      { name: "lemon", qty: "1" },
      { name: "garlic", qty: "3 cloves" },
      { name: "paprika", qty: "1 tsp" },
      { name: "olive oil", qty: "2 tbsp" },
      { name: "cucumber", qty: "1", optional: true },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Marinate chicken in lemon, garlic, paprika and oil.",
      "Cook rice; sear chicken 4–5 min per side.",
      "Slice over rice, add cucumber and yogurt.",
    ],
  },

  // ============== EVENING SNACK ==============
  {
    id: "es-masala-chai-toast",
    name: "Masala Chai & Buttered Toast",
    blurb: "Strong cardamom tea with hot buttered toast.",
    diet: "vegetarian",
    mealType: "evening_snack",
    prepMinutes: 10,
    cuisine: "Indian",
    ingredients: [
      { name: "tea", qty: "2 tsp" },
      { name: "milk", qty: "1 cup" },
      { name: "water", qty: "1 cup" },
      { name: "sugar", qty: "to taste" },
      { name: "ginger", qty: "1 inch", optional: true },
      { name: "cardamom", qty: "2 pods", optional: true },
      { name: "bread", qty: "2 slices" },
      { name: "butter", qty: "1 tbsp" },
    ],
    steps: [
      "Boil water with crushed ginger and cardamom.",
      "Add tea and sugar, then milk; simmer 2 min.",
      "Toast bread, slather with butter, serve with tea.",
    ],
  },
  {
    id: "es-aloo-tikki",
    name: "Crispy Aloo Tikki",
    blurb: "Pan-fried potato patties with chaat masala.",
    diet: "vegan",
    mealType: "evening_snack",
    prepMinutes: 25,
    cuisine: "Indian",
    ingredients: [
      { name: "potato", qty: "3" },
      { name: "onion", qty: "1" },
      { name: "green chili", qty: "1", optional: true },
      { name: "coriander", qty: "a handful", optional: true },
      { name: "chaat masala", qty: "1 tsp" },
      { name: "breadcrumbs", qty: "2 tbsp", optional: true },
      { name: "oil", qty: "for frying" },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Boil and mash potatoes; mix with chopped onion, chili, coriander, salt and chaat masala.",
      "Shape into patties, dust with breadcrumbs.",
      "Shallow-fry till deeply golden on both sides.",
    ],
  },
  {
    id: "es-bruschetta",
    name: "Tomato Bruschetta",
    blurb: "Toasted bread piled with garlicky tomato salsa.",
    diet: "vegan",
    mealType: "evening_snack",
    prepMinutes: 10,
    ingredients: [
      { name: "bread", qty: "4 slices" },
      { name: "tomato", qty: "2" },
      { name: "garlic", qty: "2 cloves" },
      { name: "olive oil", qty: "2 tbsp" },
      { name: "basil", qty: "a few leaves", optional: true },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Toast bread; rub with raw garlic.",
      "Top with chopped tomato tossed in olive oil, salt and basil.",
    ],
  },
  {
    id: "es-popcorn",
    name: "Stovetop Popcorn",
    blurb: "Hot, salty popcorn in 5 minutes flat.",
    diet: "vegan",
    mealType: "evening_snack",
    prepMinutes: 5,
    ingredients: [
      { name: "popcorn kernels", qty: "1/3 cup" },
      { name: "oil", qty: "2 tbsp" },
      { name: "salt", qty: "to taste" },
      { name: "butter", qty: "1 tbsp", optional: true },
    ],
    steps: [
      "Heat oil with 3 kernels; when they pop add the rest.",
      "Cover and shake till popping slows; salt and serve.",
    ],
  },
  {
    id: "es-cheese-toast",
    name: "Melty Cheese Toast",
    blurb: "Bread, lots of cheese, hot pan.",
    diet: "vegetarian",
    mealType: "evening_snack",
    prepMinutes: 8,
    ingredients: [
      { name: "bread", qty: "2 slices" },
      { name: "cheese", qty: "2 slices" },
      { name: "butter", qty: "1 tbsp" },
      { name: "tomato", qty: "1/2", optional: true },
    ],
    steps: [
      "Butter the bread; sandwich the cheese (and tomato).",
      "Toast in a pan till golden and oozy.",
    ],
  },
  {
    id: "es-chicken-popcorn",
    name: "Crispy Chicken Bites",
    blurb: "Pan-fried bite-size chicken in a spicy crust.",
    diet: "non-vegetarian",
    mealType: "evening_snack",
    prepMinutes: 20,
    ingredients: [
      { name: "chicken", qty: "250g" },
      { name: "flour", qty: "1/4 cup" },
      { name: "paprika", qty: "1 tsp" },
      { name: "garlic", qty: "2 cloves" },
      { name: "yogurt", qty: "2 tbsp" },
      { name: "oil", qty: "for shallow frying" },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Cube chicken; marinate in yogurt, garlic, paprika, salt.",
      "Toss in flour and shallow-fry till crisp and cooked through.",
    ],
  },

  // ============== DINNER ==============
  {
    id: "d-veg-stirfry-noodles",
    name: "Veg Stir-Fry Noodles",
    blurb: "Saucy noodles with crunchy vegetables.",
    diet: "vegan",
    mealType: "dinner",
    prepMinutes: 20,
    ingredients: [
      { name: "noodles", qty: "200g" },
      { name: "carrot", qty: "1" },
      { name: "bell pepper", qty: "1" },
      { name: "cabbage", qty: "1 cup", optional: true },
      { name: "garlic", qty: "3 cloves" },
      { name: "ginger", qty: "1 inch" },
      { name: "soy sauce", qty: "2 tbsp" },
      { name: "vinegar", qty: "1 tsp", optional: true },
      { name: "oil", qty: "2 tbsp" },
    ],
    steps: [
      "Boil noodles, drain and toss with a little oil.",
      "Stir-fry garlic, ginger and vegetables on high heat.",
      "Add noodles, soy sauce, vinegar; toss till glossy.",
    ],
  },
  {
    id: "d-roti-sabzi",
    name: "Roti & Aloo Gobi",
    blurb: "Soft rotis with cumin-spiced potato and cauliflower.",
    diet: "vegan",
    mealType: "dinner",
    prepMinutes: 35,
    cuisine: "Indian",
    ingredients: [
      { name: "flour", qty: "2 cups" },
      { name: "potato", qty: "2" },
      { name: "cauliflower", qty: "1/2 head" },
      { name: "onion", qty: "1" },
      { name: "tomato", qty: "1" },
      { name: "cumin seeds", qty: "1 tsp" },
      { name: "turmeric", qty: "1/2 tsp" },
      { name: "garam masala", qty: "1/2 tsp" },
      { name: "oil", qty: "2 tbsp" },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Knead flour with water and a pinch of salt; rest 10 min.",
      "Temper cumin in oil; add onion, then potato and cauliflower.",
      "Add tomato and spices; cover and cook till tender.",
      "Roll and cook rotis on a hot tawa.",
    ],
  },
  {
    id: "d-rajma-rice",
    name: "Rajma Rice",
    blurb: "Slow-simmered red kidney beans over basmati.",
    diet: "vegan",
    mealType: "dinner",
    prepMinutes: 40,
    cuisine: "Indian",
    ingredients: [
      { name: "rajma", qty: "1 cup" },
      { name: "rice", qty: "1 cup" },
      { name: "onion", qty: "2" },
      { name: "tomato", qty: "2" },
      { name: "ginger garlic paste", qty: "1 tbsp" },
      { name: "garam masala", qty: "1 tsp" },
      { name: "chili powder", qty: "1 tsp" },
      { name: "oil", qty: "2 tbsp" },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Soak rajma overnight; pressure cook till soft.",
      "Brown onion, add ginger garlic paste, then tomato and spices.",
      "Add rajma with cooking liquid; simmer 15 min. Serve over rice.",
    ],
  },
  {
    id: "d-veg-pulao",
    name: "Vegetable Pulao",
    blurb: "Fragrant rice with mixed vegetables and whole spices.",
    diet: "vegan",
    mealType: "dinner",
    prepMinutes: 30,
    cuisine: "Indian",
    ingredients: [
      { name: "rice", qty: "1.5 cups" },
      { name: "carrot", qty: "1" },
      { name: "peas", qty: "1/2 cup", optional: true },
      { name: "potato", qty: "1", optional: true },
      { name: "onion", qty: "1" },
      { name: "bay leaf", qty: "1", optional: true },
      { name: "cinnamon", qty: "1 stick", optional: true },
      { name: "cloves", qty: "3", optional: true },
      { name: "ginger garlic paste", qty: "1 tbsp" },
      { name: "oil", qty: "2 tbsp" },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Sauté whole spices and onion in oil.",
      "Add ginger garlic paste, then vegetables.",
      "Stir in rice, add 3 cups water and salt; cook covered till done.",
    ],
  },
  {
    id: "d-paneer-butter-masala",
    name: "Paneer Butter Masala",
    blurb: "Silky tomato cream sauce with soft paneer.",
    diet: "vegetarian",
    mealType: "dinner",
    prepMinutes: 30,
    cuisine: "Indian",
    ingredients: [
      { name: "paneer", qty: "250g" },
      { name: "tomato", qty: "4" },
      { name: "onion", qty: "1" },
      { name: "cashews", qty: "10", optional: true },
      { name: "butter", qty: "2 tbsp" },
      { name: "cream", qty: "1/4 cup", optional: true },
      { name: "ginger garlic paste", qty: "1 tbsp" },
      { name: "garam masala", qty: "1 tsp" },
      { name: "chili powder", qty: "1 tsp" },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Boil tomato, onion and cashews; blend smooth.",
      "Cook paste in butter with ginger garlic and spices till glossy.",
      "Stir in paneer and cream; simmer 5 min.",
    ],
  },
  {
    id: "d-margherita-pizza",
    name: "Skillet Margherita Pizza",
    blurb: "Hot pan crust, tomato, melty cheese, basil.",
    diet: "vegetarian",
    mealType: "dinner",
    prepMinutes: 25,
    ingredients: [
      { name: "flour", qty: "2 cups" },
      { name: "yeast", qty: "1 tsp", optional: true },
      { name: "tomato", qty: "2" },
      { name: "cheese", qty: "1 cup" },
      { name: "basil", qty: "a few leaves", optional: true },
      { name: "olive oil", qty: "2 tbsp" },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Make a quick dough with flour, yeast, salt and warm water; rest 15 min.",
      "Roll out, top with crushed tomato, cheese and basil.",
      "Cook in a hot covered skillet 8–10 min till bubbling.",
    ],
  },
  {
    id: "d-egg-fried-rice",
    name: "Egg Fried Rice",
    blurb: "Smoky wok-style rice with golden eggs.",
    diet: "eggetarian",
    mealType: "dinner",
    prepMinutes: 15,
    ingredients: [
      { name: "rice", qty: "2 cups cooked" },
      { name: "eggs", qty: "2" },
      { name: "spring onion", qty: "2 stalks", optional: true },
      { name: "garlic", qty: "3 cloves" },
      { name: "soy sauce", qty: "2 tbsp" },
      { name: "oil", qty: "2 tbsp" },
      { name: "pepper", qty: "to taste" },
    ],
    steps: [
      "Scramble eggs in hot oil; remove.",
      "Stir-fry garlic, then add cold rice and soy sauce.",
      "Return eggs, finish with pepper and spring onion.",
    ],
  },
  {
    id: "d-chicken-biryani",
    name: "One-Pot Chicken Biryani",
    blurb: "Spiced rice and chicken layered in one pot.",
    diet: "non-vegetarian",
    mealType: "dinner",
    prepMinutes: 50,
    cuisine: "Indian",
    ingredients: [
      { name: "rice", qty: "2 cups" },
      { name: "chicken", qty: "500g" },
      { name: "onion", qty: "2" },
      { name: "tomato", qty: "1" },
      { name: "yogurt", qty: "1/2 cup" },
      { name: "ginger garlic paste", qty: "1 tbsp" },
      { name: "biryani masala", qty: "2 tbsp" },
      { name: "mint", qty: "a handful", optional: true },
      { name: "coriander", qty: "a handful", optional: true },
      { name: "oil", qty: "3 tbsp" },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Brown sliced onion in oil; add ginger garlic paste.",
      "Add chicken, yogurt, tomato and biryani masala; cook 10 min.",
      "Layer with par-cooked rice, herbs, and steam covered 15 min.",
    ],
  },
  {
    id: "d-lemon-pepper-fish",
    name: "Lemon Pepper Fish",
    blurb: "Pan-seared fish with lemon, pepper and butter.",
    diet: "non-vegetarian",
    mealType: "dinner",
    prepMinutes: 15,
    ingredients: [
      { name: "fish", qty: "2 fillets" },
      { name: "lemon", qty: "1" },
      { name: "butter", qty: "2 tbsp" },
      { name: "garlic", qty: "3 cloves" },
      { name: "pepper", qty: "to taste" },
      { name: "salt", qty: "to taste" },
      { name: "parsley", qty: "a few sprigs", optional: true },
    ],
    steps: [
      "Pat fish dry; season with salt and pepper.",
      "Sear in butter 3–4 min per side with garlic.",
      "Finish with lemon juice and parsley.",
    ],
  },
  {
    id: "d-butter-chicken",
    name: "Butter Chicken",
    blurb: "Tender chicken in a rich tomato cream gravy.",
    diet: "non-vegetarian",
    mealType: "dinner",
    prepMinutes: 35,
    cuisine: "Indian",
    ingredients: [
      { name: "chicken", qty: "500g" },
      { name: "tomato", qty: "4" },
      { name: "onion", qty: "1" },
      { name: "yogurt", qty: "1/2 cup" },
      { name: "butter", qty: "3 tbsp" },
      { name: "cream", qty: "1/4 cup", optional: true },
      { name: "ginger garlic paste", qty: "1 tbsp" },
      { name: "garam masala", qty: "1 tsp" },
      { name: "chili powder", qty: "1 tsp" },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Marinate chicken in yogurt and spices for 10 minutes; sear till charred.",
      "Cook tomato and onion soft, blend smooth.",
      "Simmer puree in butter with ginger garlic and spices.",
      "Add chicken and cream; simmer 10 min.",
    ],
  },

  // ============== ADDITIONAL BREAKFAST ==============
  {
    id: "b-peanut-butter-toast",
    name: "Peanut Butter Banana Toast",
    blurb: "Crunchy toast with peanut butter, banana, and a honey drizzle.",
    diet: "vegetarian",
    mealType: "breakfast",
    prepMinutes: 4,
    ingredients: [
      { name: "bread", qty: "2 slices" },
      { name: "peanut butter", qty: "2 tbsp" },
      { name: "banana", qty: "1" },
      { name: "honey", qty: "1 tsp", optional: true },
    ],
    steps: ["Toast bread.", "Spread peanut butter, top with banana slices and honey."],
  },
  {
    id: "b-avocado-toast",
    name: "Smashed Avocado Toast",
    blurb: "Buttery avocado on toasted sourdough with chili flakes.",
    diet: "vegan",
    mealType: "breakfast",
    prepMinutes: 6,
    ingredients: [
      { name: "bread", qty: "2 slices" },
      { name: "avocado", qty: "1" },
      { name: "lemon", qty: "1 tsp juice" },
      { name: "chili flakes", qty: "pinch", optional: true },
      { name: "salt", qty: "to taste" },
    ],
    steps: ["Toast bread.", "Mash avocado with lemon and salt; spread, top with chili flakes."],
  },
  {
    id: "b-fruit-smoothie",
    name: "Berry Banana Smoothie",
    blurb: "Frosty smoothie with berries, banana, and almond milk.",
    diet: "vegan",
    mealType: "breakfast",
    prepMinutes: 4,
    ingredients: [
      { name: "banana", qty: "1" },
      { name: "berries", qty: "1 cup" },
      { name: "almond milk", qty: "1 cup" },
      { name: "oats", qty: "2 tbsp", optional: true },
    ],
    steps: ["Blend everything until smooth and pour."],
  },
  {
    id: "b-vegan-pancakes",
    name: "Fluffy Vegan Pancakes",
    blurb: "Light pancakes made with flour, oat milk, and a hint of vanilla.",
    diet: "vegan",
    mealType: "breakfast",
    prepMinutes: 15,
    ingredients: [
      { name: "flour", qty: "1 cup" },
      { name: "oat milk", qty: "1 cup" },
      { name: "baking powder", qty: "1 tsp" },
      { name: "sugar", qty: "1 tbsp" },
      { name: "vanilla", qty: "1/2 tsp", optional: true },
    ],
    steps: ["Whisk all ingredients into a smooth batter.", "Cook on a hot pan, 2 min per side."],
  },
  {
    id: "b-poha",
    name: "Lemon Poha",
    blurb: "Light flattened-rice breakfast with peanuts and curry leaves.",
    diet: "vegan",
    mealType: "breakfast",
    prepMinutes: 12,
    ingredients: [
      { name: "poha", qty: "1 cup" },
      { name: "onion", qty: "1/2" },
      { name: "peanuts", qty: "2 tbsp" },
      { name: "curry leaves", qty: "few" },
      { name: "lemon", qty: "1 tsp juice" },
      { name: "turmeric", qty: "1/4 tsp" },
      { name: "mustard seeds", qty: "1/2 tsp", optional: true },
    ],
    steps: [
      "Rinse poha and drain.",
      "Temper mustard seeds, peanuts, curry leaves; sauté onion.",
      "Add turmeric and poha; toss with lemon.",
    ],
  },
  {
    id: "b-french-toast",
    name: "Cinnamon French Toast",
    blurb: "Eggy bread soaked in cinnamon batter and pan-fried golden.",
    diet: "eggetarian",
    mealType: "breakfast",
    prepMinutes: 10,
    ingredients: [
      { name: "bread", qty: "2 slices" },
      { name: "egg", qty: "1" },
      { name: "milk", qty: "1/4 cup" },
      { name: "cinnamon", qty: "1/4 tsp" },
      { name: "sugar", qty: "1 tsp" },
      { name: "butter", qty: "1 tsp" },
    ],
    steps: [
      "Whisk egg, milk, cinnamon, sugar.",
      "Soak bread, pan-fry in butter till golden.",
    ],
  },

  // ============== ADDITIONAL MORNING SNACK ==============
  {
    id: "ms-apple-slices",
    name: "Apple Peanut Butter Slices",
    blurb: "Crisp apple slices dipped in peanut butter.",
    diet: "vegan",
    mealType: "morning_snack",
    prepMinutes: 3,
    ingredients: [
      { name: "apple", qty: "1" },
      { name: "peanut butter", qty: "2 tbsp" },
    ],
    steps: ["Slice apple.", "Serve with peanut butter."],
  },
  {
    id: "ms-trail-mix",
    name: "Sweet Trail Mix",
    blurb: "Almonds, raisins, and dark chocolate chips in a small bowl.",
    diet: "vegan",
    mealType: "morning_snack",
    prepMinutes: 2,
    ingredients: [
      { name: "almonds", qty: "1/4 cup" },
      { name: "raisins", qty: "2 tbsp" },
      { name: "dark chocolate chips", qty: "1 tbsp" },
    ],
    steps: ["Mix everything in a bowl."],
  },
  {
    id: "ms-roasted-chana",
    name: "Roasted Chana Bowl",
    blurb: "Spiced roasted chickpeas with a squeeze of lemon.",
    diet: "vegan",
    mealType: "morning_snack",
    prepMinutes: 3,
    ingredients: [
      { name: "roasted chana", qty: "1/2 cup" },
      { name: "chaat masala", qty: "1/4 tsp" },
      { name: "lemon", qty: "1 tsp juice" },
    ],
    steps: ["Toss chana with masala and lemon."],
  },
  {
    id: "ms-banana-walnut",
    name: "Banana Walnut Bites",
    blurb: "Banana coins topped with crushed walnuts and a touch of honey.",
    diet: "vegetarian",
    mealType: "morning_snack",
    prepMinutes: 3,
    ingredients: [
      { name: "banana", qty: "1" },
      { name: "walnuts", qty: "2 tbsp" },
      { name: "honey", qty: "1 tsp", optional: true },
    ],
    steps: ["Slice banana, top with crushed walnuts and honey."],
  },
  {
    id: "ms-cheese-crackers",
    name: "Cheese & Cracker Plate",
    blurb: "Crunchy crackers with sliced cheese and grapes.",
    diet: "vegetarian",
    mealType: "morning_snack",
    prepMinutes: 3,
    ingredients: [
      { name: "crackers", qty: "6" },
      { name: "cheese", qty: "50g" },
      { name: "grapes", qty: "small handful", optional: true },
    ],
    steps: ["Plate crackers with cheese slices and grapes."],
  },
  {
    id: "ms-boiled-egg-toast",
    name: "Boiled Egg on Toast",
    blurb: "A simple boiled egg, sliced over buttered toast.",
    diet: "eggetarian",
    mealType: "morning_snack",
    prepMinutes: 8,
    ingredients: [
      { name: "egg", qty: "1" },
      { name: "bread", qty: "1 slice" },
      { name: "butter", qty: "1 tsp" },
      { name: "salt", qty: "to taste" },
    ],
    steps: ["Boil egg 8 min.", "Toast bread, butter it, top with sliced egg and salt."],
  },

  // ============== ADDITIONAL LUNCH ==============
  {
    id: "l-veg-pasta",
    name: "Veggie Tomato Pasta",
    blurb: "Pasta tossed in a fresh tomato sauce with herbs.",
    diet: "vegan",
    mealType: "lunch",
    prepMinutes: 20,
    ingredients: [
      { name: "pasta", qty: "1 cup" },
      { name: "tomato", qty: "2" },
      { name: "garlic", qty: "2 cloves" },
      { name: "onion", qty: "1/2" },
      { name: "olive oil", qty: "1 tbsp" },
      { name: "basil", qty: "few leaves", optional: true },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Boil pasta till al dente.",
      "Sauté garlic and onion; add chopped tomato, cook till soft.",
      "Toss pasta in sauce with basil and salt.",
    ],
  },
  {
    id: "l-rajma-rice",
    name: "Rajma Chawal",
    blurb: "Comforting kidney bean curry served over fluffy rice.",
    diet: "vegan",
    mealType: "lunch",
    prepMinutes: 30,
    ingredients: [
      { name: "rajma", qty: "1 cup" },
      { name: "rice", qty: "1 cup" },
      { name: "onion", qty: "1" },
      { name: "tomato", qty: "2" },
      { name: "ginger garlic paste", qty: "1 tsp" },
      { name: "garam masala", qty: "1/2 tsp" },
      { name: "cumin", qty: "1/2 tsp" },
    ],
    steps: [
      "Cook soaked rajma till soft.",
      "Sauté onion, ginger garlic, tomato; add spices.",
      "Add rajma and simmer; serve over rice.",
    ],
  },
  {
    id: "l-buddha-bowl",
    name: "Veggie Buddha Bowl",
    blurb: "Quinoa, roasted veggies, chickpeas, and tahini dressing.",
    diet: "vegan",
    mealType: "lunch",
    prepMinutes: 25,
    ingredients: [
      { name: "quinoa", qty: "1/2 cup" },
      { name: "chickpeas", qty: "1/2 cup" },
      { name: "sweet potato", qty: "1" },
      { name: "spinach", qty: "1 cup" },
      { name: "tahini", qty: "1 tbsp" },
      { name: "lemon", qty: "1 tsp juice" },
      { name: "olive oil", qty: "1 tbsp" },
    ],
    steps: [
      "Cook quinoa.",
      "Roast sweet potato and chickpeas with olive oil.",
      "Assemble with spinach; drizzle tahini-lemon dressing.",
    ],
  },
  {
    id: "l-paneer-wrap",
    name: "Paneer Tikka Wrap",
    blurb: "Tortilla wrap with spiced paneer, onions, and mint chutney.",
    diet: "vegetarian",
    mealType: "lunch",
    prepMinutes: 20,
    ingredients: [
      { name: "paneer", qty: "150g" },
      { name: "tortilla", qty: "2" },
      { name: "onion", qty: "1/2" },
      { name: "yogurt", qty: "2 tbsp" },
      { name: "garam masala", qty: "1/2 tsp" },
      { name: "mint chutney", qty: "2 tbsp", optional: true },
    ],
    steps: [
      "Marinate paneer in yogurt and masala; pan-sear.",
      "Warm tortilla, fill with paneer, onion, chutney; roll.",
    ],
  },
  {
    id: "l-egg-fried-rice",
    name: "Egg Fried Rice",
    blurb: "Wok-tossed rice with scrambled egg, peas, and soy sauce.",
    diet: "eggetarian",
    mealType: "lunch",
    prepMinutes: 15,
    ingredients: [
      { name: "rice", qty: "2 cups cooked" },
      { name: "egg", qty: "2" },
      { name: "peas", qty: "1/2 cup" },
      { name: "spring onion", qty: "2 stalks" },
      { name: "soy sauce", qty: "1 tbsp" },
      { name: "garlic", qty: "2 cloves" },
      { name: "oil", qty: "1 tbsp" },
    ],
    steps: [
      "Scramble eggs and set aside.",
      "Sauté garlic; toss in peas and rice.",
      "Add eggs, soy sauce, spring onion; toss hot.",
    ],
  },
  {
    id: "l-fish-curry",
    name: "Coconut Fish Curry",
    blurb: "Mild fish curry simmered in coconut milk with curry leaves.",
    diet: "non-vegetarian",
    mealType: "lunch",
    prepMinutes: 25,
    ingredients: [
      { name: "fish", qty: "300g" },
      { name: "coconut milk", qty: "1 cup" },
      { name: "onion", qty: "1" },
      { name: "tomato", qty: "1" },
      { name: "curry leaves", qty: "few" },
      { name: "ginger garlic paste", qty: "1 tsp" },
      { name: "turmeric", qty: "1/4 tsp" },
    ],
    steps: [
      "Sauté onion, ginger garlic, tomato, curry leaves.",
      "Add turmeric and coconut milk; simmer.",
      "Slide in fish and cook 8 min.",
    ],
  },

  // ============== ADDITIONAL EVENING SNACK ==============
  {
    id: "es-veg-sandwich",
    name: "Cucumber Tomato Sandwich",
    blurb: "Cool cucumber and tomato slices in soft buttered bread.",
    diet: "vegan",
    mealType: "evening_snack",
    prepMinutes: 5,
    ingredients: [
      { name: "bread", qty: "2 slices" },
      { name: "cucumber", qty: "1/2" },
      { name: "tomato", qty: "1" },
      { name: "vegan butter", qty: "1 tsp" },
      { name: "salt", qty: "to taste" },
    ],
    steps: ["Butter bread.", "Layer cucumber, tomato; salt and close."],
  },
  {
    id: "es-bhel-puri",
    name: "Quick Bhel Puri",
    blurb: "Puffed rice tossed with onion, tomato, sev, and chutneys.",
    diet: "vegan",
    mealType: "evening_snack",
    prepMinutes: 6,
    ingredients: [
      { name: "puffed rice", qty: "2 cups" },
      { name: "onion", qty: "1/2" },
      { name: "tomato", qty: "1" },
      { name: "sev", qty: "1/4 cup" },
      { name: "tamarind chutney", qty: "1 tbsp", optional: true },
      { name: "lemon", qty: "1 tsp juice" },
    ],
    steps: ["Toss puffed rice with chopped onion, tomato, sev, chutney, and lemon."],
  },
  {
    id: "es-masala-chai",
    name: "Masala Chai & Biscuits",
    blurb: "Spiced milk tea with cardamom and ginger, paired with biscuits.",
    diet: "vegetarian",
    mealType: "evening_snack",
    prepMinutes: 8,
    ingredients: [
      { name: "tea leaves", qty: "1 tsp" },
      { name: "milk", qty: "1 cup" },
      { name: "cardamom", qty: "2 pods" },
      { name: "ginger", qty: "small piece" },
      { name: "sugar", qty: "1 tsp" },
      { name: "biscuits", qty: "2", optional: true },
    ],
    steps: [
      "Boil water with crushed cardamom and ginger.",
      "Add tea and milk; simmer 4 min.",
      "Strain, sweeten, serve with biscuits.",
    ],
  },
  {
    id: "es-corn-chaat",
    name: "Buttered Corn Chaat",
    blurb: "Sweet corn tossed in butter, lemon, and chaat masala.",
    diet: "vegetarian",
    mealType: "evening_snack",
    prepMinutes: 7,
    ingredients: [
      { name: "sweet corn", qty: "1 cup" },
      { name: "butter", qty: "1 tsp" },
      { name: "lemon", qty: "1 tsp juice" },
      { name: "chaat masala", qty: "1/4 tsp" },
      { name: "coriander", qty: "1 tbsp", optional: true },
    ],
    steps: ["Steam corn.", "Toss in butter, lemon, masala, coriander."],
  },
  {
    id: "es-egg-sandwich",
    name: "Egg Mayo Sandwich",
    blurb: "Boiled egg mashed with mayo, salt, pepper between toast.",
    diet: "eggetarian",
    mealType: "evening_snack",
    prepMinutes: 10,
    ingredients: [
      { name: "egg", qty: "2" },
      { name: "bread", qty: "2 slices" },
      { name: "mayo", qty: "2 tbsp" },
      { name: "pepper", qty: "to taste" },
      { name: "salt", qty: "to taste" },
    ],
    steps: ["Boil and mash eggs with mayo, salt, pepper.", "Spread between toasted bread."],
  },
  {
    id: "es-chicken-popcorn",
    name: "Crispy Chicken Bites",
    blurb: "Bite-sized chicken chunks coated in spiced flour and pan-fried.",
    diet: "non-vegetarian",
    mealType: "evening_snack",
    prepMinutes: 18,
    ingredients: [
      { name: "chicken", qty: "200g" },
      { name: "flour", qty: "1/4 cup" },
      { name: "egg", qty: "1" },
      { name: "paprika", qty: "1/2 tsp" },
      { name: "garlic powder", qty: "1/4 tsp" },
      { name: "salt", qty: "to taste" },
      { name: "oil", qty: "for frying" },
    ],
    steps: [
      "Cube chicken; dip in beaten egg.",
      "Coat in flour with spices.",
      "Pan-fry till golden.",
    ],
  },

  // ============== ADDITIONAL DINNER ==============
  {
    id: "d-veg-stir-fry",
    name: "Garlic Veggie Stir-Fry",
    blurb: "Crunchy vegetables tossed in soy garlic sauce over noodles.",
    diet: "vegan",
    mealType: "dinner",
    prepMinutes: 18,
    ingredients: [
      { name: "noodles", qty: "150g" },
      { name: "broccoli", qty: "1 cup" },
      { name: "bell pepper", qty: "1" },
      { name: "carrot", qty: "1" },
      { name: "garlic", qty: "3 cloves" },
      { name: "soy sauce", qty: "2 tbsp" },
      { name: "sesame oil", qty: "1 tsp", optional: true },
    ],
    steps: [
      "Boil noodles.",
      "Stir-fry garlic and veggies high heat.",
      "Toss in noodles and soy sauce.",
    ],
  },
  {
    id: "d-dal-tadka",
    name: "Dal Tadka & Roti",
    blurb: "Yellow lentils tempered with cumin and garlic, with soft roti.",
    diet: "vegan",
    mealType: "dinner",
    prepMinutes: 25,
    ingredients: [
      { name: "toor dal", qty: "1 cup" },
      { name: "tomato", qty: "1" },
      { name: "onion", qty: "1/2" },
      { name: "garlic", qty: "3 cloves" },
      { name: "cumin", qty: "1/2 tsp" },
      { name: "turmeric", qty: "1/4 tsp" },
      { name: "roti", qty: "3", optional: true },
    ],
    steps: [
      "Pressure cook dal with turmeric.",
      "Temper cumin and garlic in oil; add onion and tomato.",
      "Pour over dal, simmer; serve with roti.",
    ],
  },
  {
    id: "d-chickpea-stew",
    name: "Tomato Chickpea Stew",
    blurb: "Hearty chickpeas simmered with tomatoes, onion, and herbs.",
    diet: "vegan",
    mealType: "dinner",
    prepMinutes: 22,
    ingredients: [
      { name: "chickpeas", qty: "1.5 cups" },
      { name: "tomato", qty: "2" },
      { name: "onion", qty: "1" },
      { name: "garlic", qty: "3 cloves" },
      { name: "olive oil", qty: "1 tbsp" },
      { name: "cumin", qty: "1/2 tsp" },
      { name: "paprika", qty: "1/2 tsp" },
    ],
    steps: [
      "Sauté onion and garlic.",
      "Add tomato and spices, cook till soft.",
      "Add chickpeas and simmer 10 min.",
    ],
  },
  {
    id: "d-mushroom-risotto",
    name: "Mushroom Risotto",
    blurb: "Creamy arborio rice with mushrooms, parmesan, and white wine.",
    diet: "vegetarian",
    mealType: "dinner",
    prepMinutes: 30,
    ingredients: [
      { name: "arborio rice", qty: "1 cup" },
      { name: "mushrooms", qty: "200g" },
      { name: "vegetable stock", qty: "3 cups" },
      { name: "onion", qty: "1/2" },
      { name: "parmesan", qty: "1/4 cup" },
      { name: "butter", qty: "1 tbsp" },
      { name: "white wine", qty: "1/4 cup", optional: true },
    ],
    steps: [
      "Sauté onion and mushrooms in butter.",
      "Add rice; toast 1 min, deglaze with wine.",
      "Add stock ladle by ladle till creamy; finish with parmesan.",
    ],
  },
  {
    id: "d-shakshuka",
    name: "Shakshuka",
    blurb: "Eggs poached in a spiced tomato pepper sauce.",
    diet: "eggetarian",
    mealType: "dinner",
    prepMinutes: 22,
    ingredients: [
      { name: "egg", qty: "3" },
      { name: "tomato", qty: "3" },
      { name: "bell pepper", qty: "1" },
      { name: "onion", qty: "1" },
      { name: "garlic", qty: "2 cloves" },
      { name: "paprika", qty: "1/2 tsp" },
      { name: "cumin", qty: "1/2 tsp" },
      { name: "olive oil", qty: "1 tbsp" },
    ],
    steps: [
      "Sauté onion, pepper, garlic.",
      "Add tomato and spices, simmer till thick.",
      "Crack eggs in, cover and cook till set.",
    ],
  },
  {
    id: "d-grilled-fish",
    name: "Lemon Herb Grilled Fish",
    blurb: "Pan-grilled fish with lemon, garlic, and fresh herbs.",
    diet: "non-vegetarian",
    mealType: "dinner",
    prepMinutes: 20,
    ingredients: [
      { name: "fish", qty: "300g" },
      { name: "lemon", qty: "1" },
      { name: "garlic", qty: "3 cloves" },
      { name: "parsley", qty: "2 tbsp" },
      { name: "olive oil", qty: "2 tbsp" },
      { name: "salt", qty: "to taste" },
      { name: "pepper", qty: "to taste" },
    ],
    steps: [
      "Marinate fish in lemon, garlic, oil, salt, pepper for 10 min.",
      "Pan-grill 4 min per side.",
      "Top with parsley and lemon wedges.",
    ],
  },

  // ============== INDIAN BREAKFAST CLASSICS ==============
  {
    id: "b-aloo-paratha",
    name: "Aloo Paratha",
    blurb: "Soft whole wheat flatbread stuffed with spiced potato filling.",
    diet: "vegan",
    mealType: "breakfast",
    prepMinutes: 30,
    cuisine: "Indian",
    ingredients: [
      { name: "whole wheat flour", qty: "2 cups" },
      { name: "potato", qty: "3 boiled" },
      { name: "onion", qty: "1/2" },
      { name: "green chili", qty: "1" },
      { name: "coriander", qty: "2 tbsp" },
      { name: "garam masala", qty: "1/2 tsp" },
      { name: "cumin", qty: "1/2 tsp" },
      { name: "salt", qty: "to taste" },
      { name: "oil", qty: "2 tbsp" },
    ],
    steps: [
      "Knead flour with water and a pinch of salt into a soft dough.",
      "Mash potato with onion, chili, coriander, masala, cumin, salt.",
      "Roll dough, stuff with potato, seal and roll again.",
      "Cook on hot tawa with oil until golden on both sides.",
    ],
  },
  {
    id: "b-paneer-paratha",
    name: "Paneer Paratha",
    blurb: "Flatbread filled with crumbled paneer, herbs, and spices.",
    diet: "vegetarian",
    mealType: "breakfast",
    prepMinutes: 25,
    cuisine: "Indian",
    ingredients: [
      { name: "whole wheat flour", qty: "2 cups" },
      { name: "paneer", qty: "200g" },
      { name: "green chili", qty: "1" },
      { name: "coriander", qty: "2 tbsp" },
      { name: "garam masala", qty: "1/2 tsp" },
      { name: "salt", qty: "to taste" },
      { name: "ghee", qty: "2 tbsp" },
    ],
    steps: [
      "Knead flour into soft dough.",
      "Crumble paneer; mix with chili, coriander, masala, salt.",
      "Stuff dough balls, roll out flat.",
      "Cook on tawa with ghee until golden.",
    ],
  },
  {
    id: "b-gobhi-paratha",
    name: "Gobhi Paratha",
    blurb: "Whole wheat paratha stuffed with grated cauliflower and spices.",
    diet: "vegan",
    mealType: "breakfast",
    prepMinutes: 30,
    cuisine: "Indian",
    ingredients: [
      { name: "whole wheat flour", qty: "2 cups" },
      { name: "cauliflower", qty: "2 cups grated" },
      { name: "ginger", qty: "1 tsp grated" },
      { name: "green chili", qty: "1" },
      { name: "coriander", qty: "2 tbsp" },
      { name: "garam masala", qty: "1/2 tsp" },
      { name: "salt", qty: "to taste" },
      { name: "oil", qty: "2 tbsp" },
    ],
    steps: [
      "Squeeze water out of grated cauliflower; mix with ginger, chili, coriander, masala, salt.",
      "Stuff dough balls with the filling and roll flat.",
      "Cook on tawa with oil till crisp on both sides.",
    ],
  },
  {
    id: "b-pyaaz-paratha",
    name: "Pyaaz Paratha",
    blurb: "Onion-stuffed paratha with cumin and green chili.",
    diet: "vegan",
    mealType: "breakfast",
    prepMinutes: 25,
    cuisine: "Indian",
    ingredients: [
      { name: "whole wheat flour", qty: "2 cups" },
      { name: "onion", qty: "2 finely chopped" },
      { name: "green chili", qty: "1" },
      { name: "coriander", qty: "2 tbsp" },
      { name: "cumin", qty: "1/2 tsp" },
      { name: "ajwain", qty: "1/4 tsp", optional: true },
      { name: "salt", qty: "to taste" },
      { name: "oil", qty: "2 tbsp" },
    ],
    steps: [
      "Knead flour into a soft dough.",
      "Mix onion with chili, coriander, cumin, ajwain, salt.",
      "Stuff dough, roll, and cook on tawa with oil.",
    ],
  },
  {
    id: "b-lachha-paratha",
    name: "Lachha Paratha",
    blurb: "Multi-layered flaky paratha with crisp golden swirls.",
    diet: "vegan",
    mealType: "breakfast",
    prepMinutes: 25,
    cuisine: "Indian",
    ingredients: [
      { name: "whole wheat flour", qty: "2 cups" },
      { name: "salt", qty: "to taste" },
      { name: "oil", qty: "3 tbsp" },
    ],
    steps: [
      "Knead flour with salt and water into a soft dough; rest 15 min.",
      "Roll thin, brush with oil, fold like a fan, then coil.",
      "Roll the coil flat and cook on tawa with oil till crisp and flaky.",
    ],
  },
  {
    id: "b-chole-bhature",
    name: "Chole Bhature",
    blurb: "Sunday classic — fluffy fried bread with spicy chickpea curry.",
    diet: "vegan",
    mealType: "breakfast",
    prepMinutes: 45,
    cuisine: "Indian",
    ingredients: [
      { name: "chickpeas", qty: "1.5 cups soaked" },
      { name: "all purpose flour", qty: "2 cups" },
      { name: "yogurt", qty: "1/4 cup", optional: true },
      { name: "onion", qty: "1" },
      { name: "tomato", qty: "2" },
      { name: "ginger garlic paste", qty: "1 tsp" },
      { name: "chana masala", qty: "1 tbsp" },
      { name: "garam masala", qty: "1/2 tsp" },
      { name: "oil", qty: "for frying" },
      { name: "salt", qty: "to taste" },
    ],
    steps: [
      "Knead flour into soft dough; rest 1 hr.",
      "Pressure cook chickpeas till soft.",
      "Sauté onion, ginger garlic, tomato; add masalas and chickpeas; simmer.",
      "Roll dough into discs; deep fry till puffed.",
      "Serve hot bhature with chole.",
    ],
  },
  {
    id: "b-dosa-sambhar",
    name: "Dosa with Sambhar",
    blurb: "Crispy fermented rice crepe with lentil veggie stew.",
    diet: "vegan",
    mealType: "breakfast",
    prepMinutes: 25,
    cuisine: "South Indian",
    ingredients: [
      { name: "dosa batter", qty: "2 cups" },
      { name: "toor dal", qty: "1/2 cup" },
      { name: "tamarind", qty: "1 tbsp" },
      { name: "sambhar masala", qty: "1 tbsp" },
      { name: "tomato", qty: "1" },
      { name: "drumstick", qty: "1", optional: true },
      { name: "curry leaves", qty: "few" },
      { name: "mustard seeds", qty: "1/2 tsp" },
      { name: "oil", qty: "2 tbsp" },
    ],
    steps: [
      "Cook dal with tamarind, tomato, drumstick, sambhar masala till thick.",
      "Temper mustard seeds and curry leaves; pour over sambhar.",
      "Spread dosa batter thin on hot tawa; drizzle oil till crisp.",
      "Serve dosa hot with sambhar.",
    ],
  },
  {
    id: "b-uttapam",
    name: "Onion Tomato Uttapam",
    blurb: "Thick savoury pancake topped with onion, tomato, and chili.",
    diet: "vegan",
    mealType: "breakfast",
    prepMinutes: 12,
    cuisine: "South Indian",
    ingredients: [
      { name: "dosa batter", qty: "2 cups" },
      { name: "onion", qty: "1" },
      { name: "tomato", qty: "1" },
      { name: "green chili", qty: "1" },
      { name: "coriander", qty: "2 tbsp" },
      { name: "oil", qty: "1 tbsp" },
    ],
    steps: [
      "Pour batter on hot tawa thick; sprinkle onion, tomato, chili, coriander.",
      "Drizzle oil, cover and cook till the base is golden.",
      "Flip briefly, then serve hot.",
    ],
  },
  {
    id: "b-besan-cheela",
    name: "Besan Cheela",
    blurb: "Savoury chickpea-flour pancake with onion, tomato, and herbs.",
    diet: "vegan",
    mealType: "breakfast",
    prepMinutes: 12,
    cuisine: "Indian",
    ingredients: [
      { name: "besan", qty: "1 cup" },
      { name: "onion", qty: "1/2" },
      { name: "tomato", qty: "1" },
      { name: "green chili", qty: "1" },
      { name: "coriander", qty: "2 tbsp" },
      { name: "ajwain", qty: "1/4 tsp", optional: true },
      { name: "turmeric", qty: "1/4 tsp" },
      { name: "salt", qty: "to taste" },
      { name: "oil", qty: "2 tsp" },
    ],
    steps: [
      "Whisk besan with water into a smooth batter.",
      "Stir in onion, tomato, chili, coriander, turmeric, ajwain, salt.",
      "Pour onto hot tawa, drizzle oil, cook till golden on both sides.",
    ],
  },
  {
    id: "b-moong-cheela",
    name: "Moong Dal Cheela",
    blurb: "Protein-packed green moong dal pancake with ginger and chili.",
    diet: "vegan",
    mealType: "breakfast",
    prepMinutes: 20,
    cuisine: "Indian",
    ingredients: [
      { name: "moong dal", qty: "1 cup soaked" },
      { name: "ginger", qty: "1 tsp grated" },
      { name: "green chili", qty: "1" },
      { name: "coriander", qty: "2 tbsp" },
      { name: "onion", qty: "1/2", optional: true },
      { name: "salt", qty: "to taste" },
      { name: "oil", qty: "2 tsp" },
    ],
    steps: [
      "Blend soaked moong dal with ginger, chili, salt into a thick batter.",
      "Stir in coriander and onion.",
      "Spread on hot tawa, drizzle oil, cook till golden both sides.",
    ],
  },

  // ============== FESTIVE / WEEKEND DESSERTS ==============
  {
    id: "ms-suji-halwa",
    name: "Suji Halwa",
    blurb: "Festive semolina halwa toasted in ghee with sugar and cardamom.",
    diet: "vegetarian",
    mealType: "morning_snack",
    prepMinutes: 15,
    cuisine: "Indian",
    ingredients: [
      { name: "semolina", qty: "1 cup" },
      { name: "ghee", qty: "1/2 cup" },
      { name: "sugar", qty: "3/4 cup" },
      { name: "cardamom", qty: "1/4 tsp" },
      { name: "almonds", qty: "2 tbsp", optional: true },
      { name: "raisins", qty: "1 tbsp", optional: true },
    ],
    steps: [
      "Roast semolina in ghee on low heat till golden.",
      "Add hot water (3 cups) carefully and stir.",
      "Mix in sugar and cardamom; cook till it pulls away from the pan.",
      "Garnish with almonds and raisins.",
    ],
  },
  {
    id: "es-gajar-halwa",
    name: "Gajar Ka Halwa",
    blurb: "Slow-cooked carrot halwa rich with milk, ghee, and nuts.",
    diet: "vegetarian",
    mealType: "evening_snack",
    prepMinutes: 50,
    cuisine: "Indian",
    ingredients: [
      { name: "carrot", qty: "500g grated" },
      { name: "milk", qty: "2 cups" },
      { name: "sugar", qty: "1/2 cup" },
      { name: "ghee", qty: "3 tbsp" },
      { name: "cardamom", qty: "1/4 tsp" },
      { name: "almonds", qty: "2 tbsp", optional: true },
      { name: "khoya", qty: "1/4 cup", optional: true },
    ],
    steps: [
      "Cook carrot in milk till milk reduces and carrot softens.",
      "Add sugar and cook till liquid evaporates.",
      "Stir in ghee, cardamom, khoya; finish with almonds.",
    ],
  },
  {
    id: "es-rice-kheer",
    name: "Rice Kheer",
    blurb: "Creamy slow-cooked rice pudding with cardamom and saffron.",
    diet: "vegetarian",
    mealType: "evening_snack",
    prepMinutes: 40,
    cuisine: "Indian",
    ingredients: [
      { name: "rice", qty: "1/4 cup" },
      { name: "milk", qty: "1 liter" },
      { name: "sugar", qty: "1/2 cup" },
      { name: "cardamom", qty: "1/4 tsp" },
      { name: "saffron", qty: "few strands", optional: true },
      { name: "almonds", qty: "2 tbsp", optional: true },
      { name: "raisins", qty: "1 tbsp", optional: true },
    ],
    steps: [
      "Simmer rice in milk till soft and creamy, stirring often.",
      "Add sugar, cardamom, saffron; cook 5 more min.",
      "Garnish with almonds and raisins.",
    ],
  },
  {
    id: "es-gulab-jamun",
    name: "Gulab Jamun",
    blurb: "Soft fried milk dumplings soaked in cardamom-sugar syrup.",
    diet: "vegetarian",
    mealType: "evening_snack",
    prepMinutes: 35,
    cuisine: "Indian",
    ingredients: [
      { name: "milk powder", qty: "1 cup" },
      { name: "all purpose flour", qty: "1/4 cup" },
      { name: "ghee", qty: "1 tbsp" },
      { name: "milk", qty: "1/4 cup" },
      { name: "sugar", qty: "1.5 cups" },
      { name: "cardamom", qty: "1/4 tsp" },
      { name: "rose water", qty: "1 tsp", optional: true },
      { name: "oil", qty: "for frying" },
    ],
    steps: [
      "Boil sugar with 1.5 cups water and cardamom for syrup; add rose water.",
      "Mix milk powder, flour, ghee, milk into a soft dough.",
      "Roll smooth balls; deep fry on low heat till deep golden.",
      "Soak hot jamuns in warm syrup for 1 hour.",
    ],
  },
  {
    id: "ms-kaju-katli",
    name: "Kaju Katli",
    blurb: "Diamond-cut cashew fudge with a delicate silver leaf.",
    diet: "vegetarian",
    mealType: "morning_snack",
    prepMinutes: 25,
    cuisine: "Indian",
    ingredients: [
      { name: "cashew", qty: "1 cup" },
      { name: "sugar", qty: "1/2 cup" },
      { name: "ghee", qty: "1 tsp" },
      { name: "cardamom", qty: "1/4 tsp", optional: true },
    ],
    steps: [
      "Grind cashews into a fine powder.",
      "Make a 1-string sugar syrup; add cashew powder, cardamom.",
      "Stir till it leaves the pan; knead with ghee.",
      "Roll thin and cut diamonds.",
    ],
  },

  // ============== INDIAN DINNER CLASSICS ==============
  {
    id: "d-dal-makhani-naan",
    name: "Dal Makhani with Naan",
    blurb: "Slow-cooked black lentils in butter and cream, served with naan.",
    diet: "vegetarian",
    mealType: "dinner",
    prepMinutes: 50,
    cuisine: "Indian",
    ingredients: [
      { name: "black lentils", qty: "1 cup" },
      { name: "rajma", qty: "1/4 cup" },
      { name: "butter", qty: "3 tbsp" },
      { name: "cream", qty: "1/4 cup" },
      { name: "tomato", qty: "2" },
      { name: "onion", qty: "1" },
      { name: "ginger garlic paste", qty: "1 tsp" },
      { name: "garam masala", qty: "1/2 tsp" },
      { name: "naan", qty: "3" },
    ],
    steps: [
      "Pressure cook black lentils and rajma till very soft.",
      "Sauté onion, ginger garlic, tomato in butter; add masalas.",
      "Add lentils; simmer low 30 min, stirring often.",
      "Stir in cream; serve with naan.",
    ],
  },
  {
    id: "d-malai-kofta",
    name: "Malai Kofta",
    blurb: "Soft paneer-potato dumplings in a creamy cashew tomato gravy.",
    diet: "vegetarian",
    mealType: "dinner",
    prepMinutes: 45,
    cuisine: "Indian",
    ingredients: [
      { name: "paneer", qty: "150g" },
      { name: "potato", qty: "2 boiled" },
      { name: "cornflour", qty: "2 tbsp" },
      { name: "cashew", qty: "1/4 cup" },
      { name: "tomato", qty: "3" },
      { name: "onion", qty: "1" },
      { name: "cream", qty: "1/4 cup" },
      { name: "garam masala", qty: "1/2 tsp" },
      { name: "ginger garlic paste", qty: "1 tsp" },
      { name: "oil", qty: "for frying" },
    ],
    steps: [
      "Mash paneer and potato; bind with cornflour and salt; shape koftas.",
      "Deep fry koftas till golden.",
      "Blend cashews, tomato, onion into a smooth paste.",
      "Sauté ginger garlic, paste, masalas; add cream.",
      "Place koftas in gravy just before serving.",
    ],
  },
  {
    id: "d-paneer-butter-masala",
    name: "Paneer Butter Masala",
    blurb: "Cubes of paneer in a velvety tomato-butter gravy.",
    diet: "vegetarian",
    mealType: "dinner",
    prepMinutes: 30,
    cuisine: "Indian",
    ingredients: [
      { name: "paneer", qty: "250g" },
      { name: "tomato", qty: "4" },
      { name: "onion", qty: "1" },
      { name: "cashew", qty: "10" },
      { name: "butter", qty: "3 tbsp" },
      { name: "cream", qty: "2 tbsp" },
      { name: "ginger garlic paste", qty: "1 tsp" },
      { name: "garam masala", qty: "1/2 tsp" },
      { name: "kasuri methi", qty: "1 tsp", optional: true },
    ],
    steps: [
      "Boil tomato, onion, cashew till soft; blend smooth.",
      "Sauté ginger garlic in butter; add puree and masalas.",
      "Simmer; add paneer cubes and cream.",
      "Finish with kasuri methi.",
    ],
  },
  {
    id: "d-aloo-gobhi",
    name: "Aloo Gobhi",
    blurb: "Dry curry of potato and cauliflower with cumin and turmeric.",
    diet: "vegan",
    mealType: "dinner",
    prepMinutes: 25,
    cuisine: "Indian",
    ingredients: [
      { name: "potato", qty: "2" },
      { name: "cauliflower", qty: "1 small" },
      { name: "onion", qty: "1" },
      { name: "tomato", qty: "1" },
      { name: "ginger", qty: "1 tsp grated" },
      { name: "cumin", qty: "1/2 tsp" },
      { name: "turmeric", qty: "1/4 tsp" },
      { name: "garam masala", qty: "1/2 tsp" },
      { name: "oil", qty: "2 tbsp" },
    ],
    steps: [
      "Temper cumin in oil; sauté onion and ginger.",
      "Add tomato and spices; cook till soft.",
      "Add potato and cauliflower; cover and cook till tender.",
    ],
  },
  {
    id: "d-palak-paneer",
    name: "Palak Paneer",
    blurb: "Creamy spinach gravy with soft paneer cubes and garlic.",
    diet: "vegetarian",
    mealType: "dinner",
    prepMinutes: 25,
    cuisine: "Indian",
    ingredients: [
      { name: "spinach", qty: "500g" },
      { name: "paneer", qty: "200g" },
      { name: "onion", qty: "1" },
      { name: "tomato", qty: "1" },
      { name: "garlic", qty: "4 cloves" },
      { name: "ginger", qty: "1 tsp" },
      { name: "cumin", qty: "1/2 tsp" },
      { name: "garam masala", qty: "1/2 tsp" },
      { name: "cream", qty: "2 tbsp", optional: true },
    ],
    steps: [
      "Blanch spinach; blend smooth.",
      "Sauté cumin, garlic, ginger, onion, tomato.",
      "Add spinach puree and masalas; simmer.",
      "Stir in paneer cubes and cream.",
    ],
  },

  // ============== EXTRA INDIAN LUNCH ==============
  {
    id: "l-rajma-roti",
    name: "Rajma with Jeera Rice",
    blurb: "Comforting kidney bean curry with cumin-laced basmati.",
    diet: "vegan",
    mealType: "lunch",
    prepMinutes: 35,
    cuisine: "Indian",
    ingredients: [
      { name: "rajma", qty: "1 cup soaked" },
      { name: "rice", qty: "1 cup" },
      { name: "onion", qty: "1" },
      { name: "tomato", qty: "2" },
      { name: "ginger garlic paste", qty: "1 tsp" },
      { name: "cumin", qty: "1 tsp" },
      { name: "garam masala", qty: "1/2 tsp" },
      { name: "oil", qty: "2 tbsp" },
    ],
    steps: [
      "Pressure cook rajma till soft.",
      "Sauté onion, ginger garlic, tomato; add masalas.",
      "Add rajma and simmer.",
      "Cook rice with cumin tempering and serve together.",
    ],
  },
  {
    id: "l-chana-masala",
    name: "Chana Masala",
    blurb: "Tangy chickpea curry with onion-tomato gravy and warm spices.",
    diet: "vegan",
    mealType: "lunch",
    prepMinutes: 30,
    cuisine: "Indian",
    ingredients: [
      { name: "chickpeas", qty: "1.5 cups" },
      { name: "onion", qty: "1" },
      { name: "tomato", qty: "2" },
      { name: "ginger garlic paste", qty: "1 tsp" },
      { name: "chana masala", qty: "1 tbsp" },
      { name: "cumin", qty: "1/2 tsp" },
      { name: "oil", qty: "2 tbsp" },
    ],
    steps: [
      "Sauté cumin, onion, ginger garlic, tomato.",
      "Add chana masala and chickpeas; simmer 15 min.",
    ],
  },

  // ============== EXTRA SOUTH INDIAN SNACK ==============
  {
    id: "es-medu-vada",
    name: "Medu Vada",
    blurb: "Crispy savoury urad dal donuts with curry leaves and pepper.",
    diet: "vegan",
    mealType: "evening_snack",
    prepMinutes: 25,
    cuisine: "South Indian",
    ingredients: [
      { name: "urad dal", qty: "1 cup soaked" },
      { name: "curry leaves", qty: "few" },
      { name: "green chili", qty: "1" },
      { name: "ginger", qty: "1 tsp" },
      { name: "pepper", qty: "1/2 tsp" },
      { name: "salt", qty: "to taste" },
      { name: "oil", qty: "for frying" },
    ],
    steps: [
      "Grind soaked urad dal into a thick fluffy batter.",
      "Mix in curry leaves, chili, ginger, pepper, salt.",
      "Shape donuts and deep fry till golden.",
    ],
  },

  // ============== MORE MORNING SNACKS ==============
  {
    id: "ms-fruit-bowl",
    name: "Mixed Fruit Bowl",
    blurb: "Seasonal fruits tossed with lemon and a sprinkle of chaat masala.",
    diet: "vegan",
    mealType: "morning_snack",
    prepMinutes: 5,
    ingredients: [
      { name: "apple", qty: "1" },
      { name: "banana", qty: "1" },
      { name: "orange", qty: "1" },
      { name: "lemon", qty: "1 tsp juice" },
      { name: "chaat masala", qty: "1/4 tsp", optional: true },
    ],
    steps: ["Chop fruits and toss with lemon and chaat masala."],
  },
  {
    id: "ms-makhana",
    name: "Roasted Makhana",
    blurb: "Crunchy fox nuts roasted in ghee with pink salt and pepper.",
    diet: "vegetarian",
    mealType: "morning_snack",
    prepMinutes: 8,
    cuisine: "Indian",
    ingredients: [
      { name: "makhana", qty: "2 cups" },
      { name: "ghee", qty: "1 tsp" },
      { name: "salt", qty: "to taste" },
      { name: "pepper", qty: "1/4 tsp" },
    ],
    steps: ["Roast makhana in ghee on low heat till crisp.", "Season with salt and pepper."],
  },
  {
    id: "ms-coconut-laddu",
    name: "Coconut Laddu",
    blurb: "No-bake coconut and condensed milk laddus with cardamom.",
    diet: "vegetarian",
    mealType: "morning_snack",
    prepMinutes: 15,
    cuisine: "Indian",
    ingredients: [
      { name: "desiccated coconut", qty: "2 cups" },
      { name: "condensed milk", qty: "1 cup" },
      { name: "cardamom", qty: "1/4 tsp" },
    ],
    steps: [
      "Cook coconut and condensed milk on low till thick.",
      "Add cardamom; cool slightly and roll into balls.",
      "Roll laddus in extra coconut.",
    ],
  },
  {
    id: "ms-besan-laddu",
    name: "Besan Laddu",
    blurb: "Festive ghee-roasted gram flour laddus with sugar and cardamom.",
    diet: "vegetarian",
    mealType: "morning_snack",
    prepMinutes: 25,
    cuisine: "Indian",
    ingredients: [
      { name: "besan", qty: "2 cups" },
      { name: "ghee", qty: "1 cup" },
      { name: "powdered sugar", qty: "1 cup" },
      { name: "cardamom", qty: "1/4 tsp" },
      { name: "almonds", qty: "2 tbsp", optional: true },
    ],
    steps: [
      "Roast besan in ghee on low heat till deep golden and fragrant.",
      "Cool slightly; mix in sugar, cardamom, almonds.",
      "Shape into laddus.",
    ],
  },
  {
    id: "ms-energy-bites",
    name: "Date Almond Energy Bites",
    blurb: "No-bake bites of dates, almonds, oats, and cocoa.",
    diet: "vegan",
    mealType: "morning_snack",
    prepMinutes: 10,
    ingredients: [
      { name: "dates", qty: "1 cup pitted" },
      { name: "almonds", qty: "1/2 cup" },
      { name: "oats", qty: "1/2 cup" },
      { name: "cocoa", qty: "1 tbsp", optional: true },
    ],
    steps: ["Pulse all ingredients in a blender.", "Roll into bite-sized balls."],
  },
  {
    id: "ms-yogurt-parfait",
    name: "Yogurt Berry Parfait",
    blurb: "Layered yogurt, granola, berries, and a honey drizzle.",
    diet: "vegetarian",
    mealType: "morning_snack",
    prepMinutes: 4,
    ingredients: [
      { name: "yogurt", qty: "1 cup" },
      { name: "granola", qty: "1/4 cup" },
      { name: "berries", qty: "1/2 cup" },
      { name: "honey", qty: "1 tsp", optional: true },
    ],
    steps: ["Layer yogurt, granola, berries in a glass.", "Drizzle with honey."],
  },
  {
    id: "ms-banana-bread",
    name: "Banana Walnut Bread Slice",
    blurb: "A warm slice of homestyle banana bread with walnuts.",
    diet: "vegetarian",
    mealType: "morning_snack",
    prepMinutes: 6,
    ingredients: [
      { name: "banana bread", qty: "1 slice" },
      { name: "butter", qty: "1 tsp", optional: true },
      { name: "walnuts", qty: "1 tbsp", optional: true },
    ],
    steps: ["Warm the slice; top with butter and crushed walnuts."],
  },

  // ============== MORE LUNCHES ==============
  {
    id: "l-veg-biryani",
    name: "Veg Biryani",
    blurb: "Fragrant basmati layered with veggies, mint, and biryani masala.",
    diet: "vegan",
    mealType: "lunch",
    prepMinutes: 40,
    cuisine: "Indian",
    ingredients: [
      { name: "rice", qty: "1.5 cups basmati" },
      { name: "mixed vegetables", qty: "2 cups" },
      { name: "onion", qty: "2" },
      { name: "tomato", qty: "1" },
      { name: "ginger garlic paste", qty: "1 tbsp" },
      { name: "biryani masala", qty: "1 tbsp" },
      { name: "mint", qty: "1/4 cup" },
      { name: "coriander", qty: "1/4 cup" },
      { name: "oil", qty: "3 tbsp" },
    ],
    steps: [
      "Fry onions till golden; reserve half.",
      "Cook veggies with ginger garlic, tomato, biryani masala.",
      "Parboil rice with whole spices.",
      "Layer veggies, rice, mint, coriander, fried onion; dum 15 min.",
    ],
  },
  {
    id: "l-kadhi-chawal",
    name: "Kadhi Chawal",
    blurb: "Tangy yogurt-besan curry with pakoras served over rice.",
    diet: "vegetarian",
    mealType: "lunch",
    prepMinutes: 35,
    cuisine: "Indian",
    ingredients: [
      { name: "yogurt", qty: "2 cups" },
      { name: "besan", qty: "1/2 cup" },
      { name: "rice", qty: "1 cup" },
      { name: "onion", qty: "1" },
      { name: "ginger", qty: "1 tsp" },
      { name: "turmeric", qty: "1/4 tsp" },
      { name: "cumin", qty: "1/2 tsp" },
      { name: "mustard seeds", qty: "1/2 tsp" },
      { name: "curry leaves", qty: "few" },
      { name: "oil", qty: "2 tbsp" },
    ],
    steps: [
      "Whisk yogurt with besan, turmeric, salt and 4 cups water.",
      "Make besan-onion pakoras and fry.",
      "Temper cumin, mustard, curry leaves; add yogurt mix and simmer.",
      "Add pakoras and serve over rice.",
    ],
  },
  {
    id: "l-veg-thali",
    name: "Quick Veg Thali",
    blurb: "Roti, dal, sabzi, rice, and yogurt — a complete plate.",
    diet: "vegetarian",
    mealType: "lunch",
    prepMinutes: 35,
    cuisine: "Indian",
    ingredients: [
      { name: "roti", qty: "2" },
      { name: "rice", qty: "1/2 cup" },
      { name: "toor dal", qty: "1/2 cup" },
      { name: "mixed vegetables", qty: "1 cup" },
      { name: "yogurt", qty: "1/2 cup" },
      { name: "ghee", qty: "1 tsp" },
    ],
    steps: [
      "Cook dal with turmeric and salt; temper with ghee.",
      "Stir-fry veggies with cumin and masalas.",
      "Plate with rice, roti, and yogurt.",
    ],
  },
  {
    id: "l-tofu-stir-fry",
    name: "Tofu Veggie Stir-Fry Bowl",
    blurb: "Crispy tofu with bell peppers and broccoli over rice.",
    diet: "vegan",
    mealType: "lunch",
    prepMinutes: 22,
    ingredients: [
      { name: "tofu", qty: "200g" },
      { name: "bell pepper", qty: "1" },
      { name: "broccoli", qty: "1 cup" },
      { name: "garlic", qty: "3 cloves" },
      { name: "soy sauce", qty: "2 tbsp" },
      { name: "rice", qty: "1 cup cooked" },
      { name: "sesame oil", qty: "1 tsp", optional: true },
    ],
    steps: [
      "Pan-fry cubed tofu till golden.",
      "Stir-fry garlic, pepper, broccoli high heat.",
      "Toss in tofu and soy sauce; serve over rice.",
    ],
  },
  {
    id: "l-grilled-chicken-bowl",
    name: "Grilled Chicken Rice Bowl",
    blurb: "Spiced grilled chicken over rice with cucumber salsa.",
    diet: "non-vegetarian",
    mealType: "lunch",
    prepMinutes: 25,
    ingredients: [
      { name: "chicken", qty: "300g" },
      { name: "rice", qty: "1 cup cooked" },
      { name: "cucumber", qty: "1" },
      { name: "tomato", qty: "1" },
      { name: "lemon", qty: "1 tsp juice" },
      { name: "paprika", qty: "1/2 tsp" },
      { name: "cumin", qty: "1/2 tsp" },
      { name: "olive oil", qty: "2 tbsp" },
    ],
    steps: [
      "Marinate chicken in oil, paprika, cumin, salt; grill till cooked.",
      "Dice cucumber and tomato with lemon for salsa.",
      "Serve chicken over rice with salsa.",
    ],
  },

  // ============== MORE EVENING SNACKS ==============
  {
    id: "es-pakora",
    name: "Onion Pakora",
    blurb: "Crispy gram-flour onion fritters perfect with chai.",
    diet: "vegan",
    mealType: "evening_snack",
    prepMinutes: 15,
    cuisine: "Indian",
    ingredients: [
      { name: "onion", qty: "2 sliced" },
      { name: "besan", qty: "1 cup" },
      { name: "green chili", qty: "1" },
      { name: "coriander", qty: "2 tbsp" },
      { name: "ajwain", qty: "1/4 tsp", optional: true },
      { name: "salt", qty: "to taste" },
      { name: "oil", qty: "for frying" },
    ],
    steps: [
      "Toss onion with besan, chili, coriander, ajwain, salt and a little water.",
      "Drop spoonfuls into hot oil and fry till crisp.",
    ],
  },
  {
    id: "es-aloo-tikki",
    name: "Aloo Tikki",
    blurb: "Crispy spiced potato patties served with chutney.",
    diet: "vegan",
    mealType: "evening_snack",
    prepMinutes: 20,
    cuisine: "Indian",
    ingredients: [
      { name: "potato", qty: "4 boiled" },
      { name: "green chili", qty: "1" },
      { name: "coriander", qty: "2 tbsp" },
      { name: "garam masala", qty: "1/2 tsp" },
      { name: "cornflour", qty: "2 tbsp" },
      { name: "salt", qty: "to taste" },
      { name: "oil", qty: "3 tbsp" },
    ],
    steps: [
      "Mash potato with chili, coriander, masala, cornflour, salt.",
      "Shape patties; pan-fry till golden and crisp.",
    ],
  },
  {
    id: "es-veg-spring-rolls",
    name: "Veggie Spring Rolls",
    blurb: "Crisp rolls stuffed with cabbage, carrot, and spring onion.",
    diet: "vegan",
    mealType: "evening_snack",
    prepMinutes: 25,
    ingredients: [
      { name: "spring roll sheets", qty: "8" },
      { name: "cabbage", qty: "1 cup shredded" },
      { name: "carrot", qty: "1 grated" },
      { name: "spring onion", qty: "2 stalks" },
      { name: "soy sauce", qty: "1 tbsp" },
      { name: "garlic", qty: "2 cloves" },
      { name: "oil", qty: "for frying" },
    ],
    steps: [
      "Stir-fry garlic and veggies with soy sauce.",
      "Wrap in sheets, seal with water, and deep fry till golden.",
    ],
  },
  {
    id: "es-paneer-tikka",
    name: "Paneer Tikka",
    blurb: "Smoky char-grilled paneer cubes with peppers and onion.",
    diet: "vegetarian",
    mealType: "evening_snack",
    prepMinutes: 20,
    cuisine: "Indian",
    ingredients: [
      { name: "paneer", qty: "250g cubed" },
      { name: "bell pepper", qty: "1" },
      { name: "onion", qty: "1" },
      { name: "yogurt", qty: "1/4 cup" },
      { name: "tikka masala", qty: "1 tbsp" },
      { name: "ginger garlic paste", qty: "1 tsp" },
      { name: "lemon", qty: "1 tsp juice" },
      { name: "oil", qty: "1 tbsp" },
    ],
    steps: [
      "Mix yogurt with tikka masala, ginger garlic, lemon.",
      "Marinate paneer and veggies 15 min.",
      "Skewer and pan-grill or air-fry till charred.",
    ],
  },
  {
    id: "es-samosa",
    name: "Aloo Samosa",
    blurb: "Crispy pastry pockets stuffed with spiced potato and peas.",
    diet: "vegan",
    mealType: "evening_snack",
    prepMinutes: 45,
    cuisine: "Indian",
    ingredients: [
      { name: "all purpose flour", qty: "1.5 cups" },
      { name: "potato", qty: "3 boiled" },
      { name: "peas", qty: "1/2 cup" },
      { name: "ginger", qty: "1 tsp" },
      { name: "green chili", qty: "1" },
      { name: "garam masala", qty: "1/2 tsp" },
      { name: "cumin", qty: "1/2 tsp" },
      { name: "oil", qty: "for frying" },
    ],
    steps: [
      "Make stiff dough with flour, salt, oil, and water; rest 20 min.",
      "Sauté cumin, ginger, chili; add potato, peas, masala.",
      "Roll dough, cut, shape cones, stuff and seal.",
      "Deep fry on low heat till crisp golden.",
    ],
  },
];

export function getRecipeById(id: string): Recipe | undefined {
  return RECIPES.find((r) => r.id === id);
}
